runtime: python38
instance_class: F2
service: service-name
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker package_name.module_name:app

env_variables:
  ENV_VAR_1: "XXXX"

handlers:
  - url: /.*
    script: auto